@hostname=localhost
@port=8080

POST http://{{hostname}}:{{port}}/workflows HTTP/1.1

{
    "workflow_name": "test_workflow_1",
    "app_id": "f5f03127-040f-4bbf-9083-b257dfaef684",
    "is_full_page_recog": "true",
    "skip_img_enhancement": "false",
    "expect_diff_images": "false"
}