@hostname=localhost
@port=8080

POST http://{{hostname}}:{{port}}/templates HTTP/1.1
Content-Type: multipart/form-data; boundary=TestBoundary

--TestBoundary
Content-Disposition: form-data; name="data"

{
    "template_name": "test_template_2",
    "width": 340.3,
    "height": 120.7,
    "fields": [
        {
            "field_name": "test_field_1",
            "width": 53.21,
            "height": 8.432,
            "x_pos": 32.11,
            "y_pos": 44.98,
            "expected_value": "test_value",
            "is_identifying": "true"
        },
        {
            "field_name": "test_field_2",
            "width": 53.21,
            "height": 12.1,
            "x_pos": 1,
            "y_pos": 1,
            "expected_value": "test_value",
            "is_identifying": "false"
        }
    ]
}

--TestBoundary
Content-Disposition: form-data; name="template"; filename="repo_screenshot_2.jpg"
Content-Type: image/jpg

--TestBoundary--