version: "3.9"

services:
  app:
    env_file:
      - .env
    container_name: workflow-service
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8443"
    depends_on:
      migrate:
        condition: service_completed_successfully
  
  migrate:
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ./database/migrations:/migrations
    command:
      [ "-path", "/migrations", "-database", "${PROD_DB}", "up"]