@hostname=localhost
@port=8080

###
# @name createApp
POST http://{{hostname}}:{{port}}/apps HTTP/1.1

{
    "app_name": "test_app"
}

?? status == 201

###
@appId = {{JSON.parse(createAppResponse.body)["Id"]}}

# @name getApp
GET http://{{hostname}}:{{port}}/apps/{{appId}} HTTP/1.1

?? status == 200

###
PATCH http://{{hostname}}:{{port}}/apps/{{appId}} HTTP/1.1

{
    "new_app_name": "test_app_333"
}

?? status == 200

###
DELETE http://{{hostname}}:{{port}}/apps/{{appId}} HTTP/1.1

?? status == 200