name: Deploy to Azure
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registery:
    name: Push container registery
    runs-on: ubuntu-latest
    environment: Docker Hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Create .env file
        env:
          PROD_DB: ${{ secrets.PROD_DB_STRING }}
        run: |
          touch .env
          echo "$PROD_DB" > .env
          cat .env
